---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-manager
  labels:
    app: rbac-manager

---
# Source: rbac-manager/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-manager
  namespace: rbac-manager
  labels:
    app: rbac-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rbac-manager
  labels:
    app: rbac-manager
rules:
  - apiGroups:
      - rbacmanager.reactiveops.io
    resources:
      - rbacdefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
      - authorization.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - "" # core
    resources:
      - serviceaccounts
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rbac-manager
  labels:
    app: rbac-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-manager
subjects:
  - kind: ServiceAccount
    name: rbac-manager
    namespace: "rbac-manager"

---
# Source: rbac-manager/templates/customresourcedefinition.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: rbac-manager
    api: rbac-manager
    kubebuilder.k8s.io: 0.1.11
  name: rbacdefinitions.rbacmanager.reactiveops.io
spec:
  group: rbacmanager.reactiveops.io
  names:
    kind: RBACDefinition
    plural: rbacdefinitions
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        rbacBindings:
          items:
            properties:
              clusterRoleBindings:
                items:
                  properties:
                    clusterRole:
                      type: string
                  required:
                  - clusterRole
                  type: object
                type: array
              name:
                type: string
              roleBindings:
                items:
                  properties:
                    clusterRole:
                      type: string
                    namespace:
                      type: string
                    role:
                      type: string
                  type: object
                type: array
              subjects:
                items:
                  type: object
                type: array
            required:
            - name
            - subjects
            type: object
          type: array
        status:
          type: object
      required:
      - metadata
      - rbacBindings
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null

---
# Source: rbac-manager/templates/controller.yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rbac-manager
  namespace: rbac-manager
  labels:
    app: rbac-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-manager
      release: rbac-manager
  template:
    metadata:
      labels:
        app: rbac-manager
        release: rbac-manager
    spec:
      serviceAccountName: rbac-manager
      containers:
      - name: rbac-manager
        image: "quay.io/reactiveops/rbac-manager:0.4.3"
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1200
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi

---
# Source: rbac-manager/templates/create-rbac-definition.yaml
# This contains a job that will create a RBACDefinition
# based on Helm values as a post install or upgrade hook